import Link from 'next/link';

const paths=[['Give Sneakers','/give','Donate or host a collection.'],['Request Support','/request','Submit a person or organization need.'],['Volunteer','/volunteer','Help collect, prepare, and distribute.'],['Partner','/partners','Build reach, operations, and impact.']];

export default function Home(){return <main>
  <header className="header"><Link href="/"><img src="/brand/sole-logo.png" alt="The Sole Exchange"/></Link><nav><Link href="/about">About</Link><Link href="/give">Give</Link><Link href="/request">Request</Link><Link href="/volunteer">Volunteer</Link><Link href="/impact">Impact</Link></nav><Link className="primary actions" href="/connect">Get involved</Link></header>
  <section className="hero"><div className="hero-copy"><small>Air Force One’s Drive</small><h1>Give a pair.<br/>Move a life.</h1><p>The Sole Exchange turns sneaker culture into practical support—collecting, preparing, and placing quality footwear through responsible community partnerships.</p><div className="actions"><Link className="primary" href="/give">Give sneakers</Link><Link href="/request">Request support</Link></div></div><div className="hero-art"><img src="/brand/sole-hero.png" alt="Sole Exchange community sneaker drive"/><img src="/brand/sole-logo.png" alt=""/></div></section>
  <section className="impact"><div><b>Give</b><span>Quality footwear</span></div><div><b>Prepare</b><span>Sort, clean, pair</span></div><div><b>Place</b><span>Responsible distribution</span></div><div><b>Report</b><span>Transparent impact</span></div></section>
  <section className="programs"><div className="sectionHead"><h2>One exchange.<br/>Four ways in.</h2><p>Every path begins with a clear request, confirmed capacity, responsible handoff, and respect for the people receiving support.</p></div><div className="programGrid">{paths.map(([title,href,copy],i)=><Link key={href} href={href}><small>0{i+1}</small><h3>{title}</h3><p>{copy}</p><span>Open path ↗</span></Link>)}</div></section>
  <section className="story"><img src="/brand/drive-archive.png" alt="Sole Exchange Air Force One’s Drive"/><div><small className="kicker">The program</small><h2>Sneaker culture, put to work.</h2><p>The Sole Exchange is building a repeatable system for drives, volunteers, schools, community organizations, product partners, and recipients. The goal is not simply to collect—it is to deliver usable pairs through a documented, dignified process.</p><div className="actions"><Link className="primary" href="/about">Read the mission</Link><Link href="/schools">Schools & community</Link></div></div></section>
  <section className="cta"><h2>The next pair can start here.</h2><p>Give, request, volunteer, host a collection, or bring your organization into the exchange.</p><Link href="/connect">Choose your path</Link></section>
  <footer className="footer"><img src="/brand/sole-logo.png" alt=""/><span>© 2026 The Sole Exchange · Air Force One’s Drive</span></footer>
</main>}
