import Link from 'next/link';
import {notFound} from 'next/navigation';
import {pages,pageKeys} from '../data';

const roles=['Collect','Inspect','Clean','Pair','Label','Pack','Transport','Distribute'];
const requestSteps=[['01','Name the need','Who needs support, where, why, and by when.'],['02','Define the sizes','Share size ranges and quantities without sending sensitive records.'],['03','Confirm stewardship','Identify who receives, stores, fits, and distributes each pair.'],['04','Match responsibly','The team confirms what inventory, timing, and delivery are actually possible.']];

function Header(){return <header className="header detailHeader"><Link href="/"><img src="/brand/sole-logo.png" alt="The Sole Exchange"/></Link><nav><Link href="/about">About</Link><Link href="/give">Give</Link><Link href="/request">Request</Link><Link href="/volunteer">Volunteer</Link><Link href="/impact">Impact</Link></nav><Link className="primary detailAction" href="/#exchange-form">Get involved</Link></header>}
function Footer(){return <footer className="footer"><img src="/brand/sole-logo.png" alt=""/><span>© 2026 The Sole Exchange · Sneaker culture, put to work.</span></footer>}

function Feature({slug}){
  if(slug==='about')return <section className="soleFeature soleManifesto"><img src="/brand/drive-archive.png" alt="Air Force One’s Drive archive"/><div><small>Why this exists</small><blockquote>Access begins at ground level.</blockquote><p>A dependable pair can affect whether someone participates in school, work, sport, community, and daily life. The Sole Exchange turns an ordinary object into a disciplined system of collection, care, and placement.</p></div></section>;
  if(slug==='give')return <section className="soleFeature giveGuide"><div><small>Condition standard</small><h2>Would you give this pair to someone you know?</h2><p>If the answer is not an immediate yes, it does not belong in the distribution stream.</p><ul><li>Clean interior and exterior</li><li>Wearable sole and secure upper</li><li>Complete pair with usable laces</li><li>Size clearly labeled</li></ul></div><img src="/brand/sole-hero.png" alt="Sole Exchange sneaker drive"/></section>;
  if(slug==='request')return <section className="requestFlow"><div><small>Responsible request flow</small><h2>Need first.<br/>Inventory second.</h2></div><ol>{requestSteps.map(([n,t,c])=><li key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></li>)}</ol></section>;
  if(slug==='volunteer')return <section className="roleBoard"><div><small>The service line</small><h2>Every pair passes through hands that care.</h2></div><div>{roles.map((role,i)=><span key={role}><b>{String(i+1).padStart(2,'0')}</b>{role}</span>)}</div></section>;
  if(slug==='schools')return <section className="schoolBlueprint"><div><small>School and community blueprint</small><h2>One activation.<br/>Four accountable stages.</h2></div><ol><li><b>Host</b><span>Confirm audience, dates, staff, storage, safeguarding, and campaign message.</span></li><li><b>Collect</b><span>Receive only approved items and document every handoff.</span></li><li><b>Prepare</b><span>Inspect, clean, pair, size, inventory, and pack through a controlled service day.</span></li><li><b>Place</b><span>Fit and distribute with privacy, choice, dignity, and a responsible staff lead.</span></li></ol></section>;
  if(slug==='partners')return <section className="partnerChain"><small>Partnership value chain</small><div>{[['Product','Footwear, care supplies, packaging'],['Place','Collection, storage, distribution'],['Movement','Logistics, volunteers, transport'],['Capital','Operations, documentation, scale'],['Trust','Schools, programs, community relationships']].map(([t,c],i)=><article key={t}><b>{String(i+1).padStart(2,'0')}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section>;
  if(slug==='impact')return <section className="impactLedger"><div><small>The impact ledger</small><h2>Count the chain,<br/>not only the total.</h2><p>Until the archive is reconciled, the site will not publish invented totals. The operating ledger is designed to make every approved batch traceable.</p></div><dl>{['Received','Rejected','Restored','Paired','Packed','Transferred','Distributed','Confirmed fit'].map((x,i)=><div key={x}><dt>{String(i+1).padStart(2,'0')}</dt><dd>{x}</dd><span>Verified data only</span></div>)}</dl></section>;
  return <section className="faqExperience"><div><small>Before you act</small><h2>Confirm the current drive.</h2><p>Locations, capacity, sizes, dates, and available inventory change. An old flyer is not an active promise.</p></div><div>{pages.faq[2].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>;
}

export function generateStaticParams(){return pageKeys.map(slug=>({slug}))}
export async function generateMetadata({params}){const {slug}=await params;const p=pages[slug];return p?{title:`${p[0]} — The Sole Exchange`,description:p[1],alternates:{canonical:`/${slug}`}}:{}}
export default async function Page({params}){const {slug}=await params;const p=pages[slug];if(!p)notFound();return <main className={`detailPage detail-${slug}`}><Header/><section className="detailHero elevatedHero"><small className="kicker">The Sole Exchange / {slug}</small><h1>{p[0]}</h1><p>{p[1]}</p><div className="actions"><Link className="primary" href="/#exchange-form">Start here</Link><Link href="/faq">Read FAQ</Link></div></section><Feature slug={slug}/>{slug!=='faq'&&<section className="detailGrid elevatedGrid">{p[2].map(([h,b],i)=><article key={h}><small>0{i+1}</small><h2>{h}</h2><p>{b}</p></article>)}</section>}<section className="cta elevatedCta"><small>Move with purpose</small><h2>Put a pair in motion.</h2><p>Choose the request type and give the team enough detail to route it responsibly.</p><Link href="/#exchange-form">Open the form</Link></section><Footer/></main>}
